config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :projects do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :projects
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :user
  belongs_to :category
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :projects
  has_many :comments
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_project
  before_action :find_comment, only: [:edit, :update, :destroy]

  def new
    @comment = Comment.new
  end


  def create
    @comment = Comment.new(comment_params)
    @comment.project_id = @project.id
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to project_path(@project)
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to project_path(@project)
  end



  private

  def comment_params
    params.require(:comment).permit([:rating, :commenter, :comment])
  end

  def find_project
    @project = Project.find(params[:project_id])
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.order("created_at DESC")
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    # @project = Project.new
    @project = current_user.projects.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  # GET /projects/1/edit
  def edit
    # allow access to category_id when editing
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)
    @project.category_id = params[:category_id]

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    @project.category_id = params[:category_id]
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :image, :category_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

  def update
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:user).permit(:email, :avatar)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.haml
#comments
  .container
    %h4 Rating: 
    = comment.rating
    %p Comment by:
    = comment.commenter = current_user.email
    %p Comment:
    = comment.comment

    %br/

    = link_to "Edit", edit_project_comment_path(comment.project, comment), class: "btn btn-primary"
    = link_to "Delete", project_comment_path(comment.project, comment), method: :delete, date: { confirm: "Are You Sure?" }, class: "btn btn-danger"

    %br/

app/views/comments/_form.html.haml
#form-horizontal
  = simple_form_for([@project, @project.comments.build]) do |f|
    .field
      = f.input :rating
      
      = f.input :comment
    .field
      = f.submit 'Save', class: "btn btn-success"

app/views/comments/edit.html.haml
#edit_form
  %h2 Edit Form
  = simple_form_for([@project, @comment]) do |f|
    = f.input :rating
    = f.input :comment
    = f.submit "Update Comment", class: "btn btn-success"

app/views/comments/new.html.haml
#new_comment
  .container
    = render 'form'

app/views/layouts/_header.html.haml
#header
  -# .container
  .navbar.navbar-inverse
    .nav.navbar-header
      = link_to "Project Home", root_path, class: "navbar-brand"
    .nav.navbar-nav.pull-left
      %li.dropdown
        %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          Categories
          %span.caret
        %ul.dropdown-menu{:role => "menu"}
          %li
            %a{:href => "#"} Action
          %li
            %a{:href => "#"} Another action
          %li
            %a{:href => "#"} Something else here
          %li.divider{:role => "separator"}
          %li
            %a{:href => "#"} Separated link
          -# - Category.all.each do |category|
          -#   -# %li{:class => 'active' if params[:category] == category.name}
          -#   = link_to category.name, projects_path(category: category.name), class: "link"

    

    .nav.navbar-nav.pull-right
      -# = link_to "Log Out", root_path, class: "btn btn-default"
      -# = link_to "Sign In", root_path, class: "btn btn-primary"
      -# = link_to "Log In", root_path, class: "btn btn-default"
      - if user_signed_in?
        = link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'btn btn-danger'
      - else
        = link_to 'Sign Up', new_user_registration_path , class: 'btn btn-default'
        = link_to 'Log In', new_user_session_path , class: 'btn btn-default'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Rating

    %meta{charset: "utf-8"}/
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    %link{:type => "text/css", :rel => "stylesheet", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"}
    %link{:type => "text/css", :rel => "stylesheet", :href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"}
    %link{:type => "text/css", :rel => "stylesheet", :href => 'http://fonts.googleapis.com/css?family=Open+Sans' }
    %link{:type => "text/css", :rel => "stylesheet", :href => 'http://fonts.googleapis.com/css?family=Shadows+Into+Light' }
    %link{:href => "//cdn-images.mailchimp.com/embedcode/classic-10_7.css", :rel => "stylesheet", :type => "text/css"}/

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %script{:type => "text/javascript", :src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"}
    %script{:src => "//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js", :type => "text/javascript"}
    = csrf_meta_tags


  %body

    - if notice
      %p.alert.alert-success= notice
    - if alert
      %p.alert.alert-danger= alert

    = render '/layouts/header'
    .container
      = yield

app/views/projects/_form.html.haml
-# = form_for @project do |f|
#form
  .container
    .col-md-6.col-md-offset-3

      = simple_form_for @project, html: { :multipart => true } do |f|
        - if @project.errors.any?
          #error_explanation
            %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
            %ul
              - @project.errors.full_messages.each do |msg|
                %li= msg


        .field
          = select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category")
        .field
          = f.input :title, label: "Project Title"
          = f.input :description
        .field
          = f.input :image, as: :file
          = f.submit 'Save', class: "btn btn-success"

        -#
        -# .field
        -#   = select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category")
        -# .field
        -#   = f.label :title
        -#   = f.text_field :title
        -# .field
        -#   = f.label :description
        -#   = f.text_area :description
        -# .field
        -#   = f.input :image, as: :file
        -# .actions
        -#   = f.submit 'Save'

app/views/projects/edit.html.haml
-# = form_for @project do |f|
#form
  .container
    .col-md-6.col-md-offset-3
      %h1 Editing project


      = simple_form_for @project, html: { :multipart => true } do |f|
        - if @project.errors.any?
          #error_explanation
            %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
            %ul
              - @project.errors.full_messages.each do |msg|
                %li= msg

        .field.form-horizontal
          = f.select :category_id, @categories
        .field.form-horizontal
          = f.label :title
          = f.text_field :title
        .field
          = f.label :description
          = f.text_area :description
        .field
          = f.input :image, as: :file
        .actions
          = f.submit 'Save'

      -# = render 'form'

      = link_to 'Show', @project, class: "btn btn-default"
      \|
      = link_to 'Back', projects_path, class: "btn btn-default"

app/views/projects/index.html.haml
#project_board
  .container
    .row#listing
      %h1 Listing projects

    - @projects.each_slice(3) do |boards|
      .row#boards
        -# - boards.each do |board|
        -# = image_tag project.image.url(:medium)
        -# %h4= project.title
        -# %p= project.description
        - boards.each do |board|
          .card
            .col-md-4#boards
              .card-img-top
                = image_tag board.image.url(:medium)
              .card-block
                %p= board.category.name
                = link_to board.title, board
                %p= board.description

%br


- if user_signed_in?
  = link_to 'New Project', new_project_path, class: "btn btn-success"

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
.container
  .row
    .col-md-4
      = image_tag @project.image.url(:medium)
    .col-md-6
      %p#notice= notice

      %p
        %b Title:
        = @project.title
      %p
        %b Category:
        = @project.category.name
      %p
        %b Description:
        = @project.description

  .row 
    .col-md-6
      = render @project.comments

      - if user_signed_in?
        = link_to "Add Comment", new_project_comment_path(@project), class: "btn btn-primary"

        - if @project.user_id == current_user.id
          = link_to 'Edit', edit_project_path(@project), class: "btn btn-primary", class: "btn btn-primary"
          \|
          = link_to 'Destroy', project_path, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-danger"


      = link_to 'Back', projects_path, class: "btn btn-default"